// core/compiler.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chokidar from 'chokidar';
import * as cheerio from 'cheerio';

// Resolve absolute paths for ES Modules compatibility
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

console.log("🚀 JSForm Compiler starting...");

// ==========================================
// 1. PROJECT SCAFFOLDING
// Automatically creates the required directory structure.
// ==========================================
const baseFolders = [
    'assets/css',
    'assets/img',
    'assets/vendors',
    'app/forms',
    'app/services'
];

console.log("🛠️  Checking project structure...");
baseFolders.forEach(folder => {
    const fullPath = path.join(rootDir, folder);
    if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
        console.log(`   -> [Created] Folder: ${folder}`);
    }
});

// ==========================================
// 2. FILE WATCHER INITIALIZATION
// Monitors the 'app/forms' directory for changes.
// ==========================================
const formsDir = path.join(rootDir, 'app', 'forms');

const watcher = chokidar.watch(formsDir, {
    ignored: /node_modules/,
    persistent: true,
    ignoreInitial: true // Prevents firing events for existing files on startup
});

watcher.on('ready', () => {
    console.log("\n👀 JSForm is ready. Create a new folder in app/forms to generate a module!");
});

// ==========================================
// 3. AUTO-GENERATION ON FOLDER CREATION
// Scaffolds the .html, .designer.js, and .controller.js files.
// ==========================================
watcher.on('addDir', (dirPath) => {
    if (dirPath === formsDir) return; // Ignore the root forms directory

    const folderName = path.basename(dirPath);
    const baseName = folderName;
    const className = folderName.charAt(0).toUpperCase() + folderName.slice(1);

    const htmlFile = path.join(dirPath, `${baseName}.html`);
    const designerFile = path.join(dirPath, `${baseName}.designer.js`);
    const controllerFile = path.join(dirPath, `${baseName}.controller.js`);

    if (!fs.existsSync(htmlFile)) {
        console.log(`\n[JSForm] 🌟 New view detected: ${folderName}. Generating skeleton...`);

        // HTML Template
        const htmlContent = `<div id="${baseName}Panel">\n    <h2>View: ${className}</h2>\n    \n</div>`;
        fs.writeFileSync(htmlFile, htmlContent);

        const propName = baseName.replace(/-([a-z0-9])/g, g => g[1].toUpperCase());
        const designerContent = `// AUTO-GENERATED BY JSFORM - DO NOT MODIFY
export class ${className}Designer {
    constructor() {
        this.autoBindEvents();
        return new Proxy(this, {
            get(target, prop) {
                if (prop in target) {
                    return target[prop];
                }
                if (typeof prop === 'string' && prop !== 'then' && !prop.startsWith('_')) {
                    const el = document.getElementById(prop);
                    if (el) return el;
                }
                return undefined;
            }
        });
    }

    get ${propName}Panel() {
        return document.getElementById('${baseName}Panel');
    }

    /**
     * Selects multiple elements within this view
     * @param {string} selector - CSS Selector (e.g., '.my-class', '[data-id]')
     * @returns {Array<HTMLElement>} Native array with the found elements
     */
    query(selector) {
        const root = document.getElementById('${baseName}Panel') || document;
        return Array.from(root.querySelectorAll(selector));
    }

    // ==========================================
    // JSFORM AUTO-BINDING ENGINE (Reflection & Event Delegation)
    // ==========================================
    autoBindEvents() {
        const methods = Object.getOwnPropertyNames(Object.getPrototypeOf(this));
        const rootElement = document.getElementById('${baseName}Panel') || document;
        methods.forEach(method => {
            if (method.includes('_') && !method.startsWith('_')) {
                const lastUnderscore = method.lastIndexOf('_');
                const targetName = method.substring(0, lastUnderscore);
                const eventType = method.substring(lastUnderscore + 1);

                if (targetName.startsWith('cls_') && typeof this[method] === 'function') {
                    const rawClassName = targetName.substring(4);
                    const className = rawClassName.replace(/_/g, '-');
                    rootElement.addEventListener(eventType, (e) => {
                        const targetElement = e.target.closest('.' + className) || e.target.closest('.' + rawClassName);
                        if (targetElement && (rootElement === document || rootElement.contains(targetElement))) {
                            this[method](e, targetElement);
                        }
                    });
                    console.log(\`[JSForm AutoBind Class - Delegated] .\${className} -> \${eventType}\`);
                } else if (typeof this[method] === 'function') {
                    rootElement.addEventListener(eventType, (e) => {
                        const targetElement = e.target.closest('#' + targetName);
                        if (targetElement && (rootElement === document || rootElement.contains(targetElement))) {
                            this[method](e, targetElement);
                        }
                    });
                    console.log(\`[JSForm AutoBind ID - Delegated] #\${targetName} -> \${eventType}\`);
                }
            }
        });
    }
}
`;
        fs.writeFileSync(designerFile, designerContent);

        // Controller Template (Clean Business Logic)
        const controllerContent = `import { ${className}Designer } from './${baseName}.designer.js';

export class ${className}Controller extends ${className}Designer {
    constructor(parameters) {
        super();
        this.parameters = parameters;
        this.init();
    }

    init() {
        console.log("${className} view loaded successfully.");
        // Ya no necesitas hacer this.btnSave.onclick = ...
        // Simplemente crea el método btnSave_click(e) { ... } abajo
    }

    // onDestroy() {
    //    // Limpieza de memoria (timers, eventos globales, etc.)
    // }
}\n`;
        fs.writeFileSync(controllerFile, controllerContent);

        console.log(`   -> ✅ Files created: .html, .designer.js, and .controller.js`);
    }
});

// ==========================================
// 4. DESIGNER UPDATE ON HTML MODIFICATION
// Parses the HTML AST and updates DOM bindings in the Designer class.
// ==========================================
watcher.on('change', (filePath) => {
    if (filePath.endsWith('.html')) {
        console.log(`\n[JSForm] 💾 HTML modified: ${path.basename(filePath)}. Updating Designer...`);
        generateDesigner(filePath);
    }
});

/**
 * Parses an HTML file and generates the corresponding .designer.js class.
 * @param {string} htmlPath - Absolute path to the HTML file.
 */
function generateDesigner(htmlPath) {
    try {
        const htmlContent = fs.readFileSync(htmlPath, 'utf-8');
        
        // Handle different cheerio module export styles
        const loadCheerio = cheerio.load || cheerio.default.load;
        const $ = loadCheerio(htmlContent);
        
        // Extract all elements with an 'id' attribute
        const elementsWithId = [];
        $('[id]').each((index, element) => {
            elementsWithId.push($(element).attr('id'));
        });

        const folderName = path.basename(path.dirname(htmlPath));
        const baseName = path.basename(htmlPath, '.html');
        const className = folderName.charAt(0).toUpperCase() + folderName.slice(1);

        const rootId = elementsWithId.includes(`${baseName}Panel`) ? `${baseName}Panel` : (elementsWithId[0] || `${baseName}Panel`);

        // Build the ES6 class code
        let jsCode = `// AUTO-GENERATED BY JSFORM - DO NOT MODIFY\nexport class ${className}Designer {\n    constructor() {\n`;
        jsCode += `        this.autoBindEvents();\n`;
        jsCode += `        return new Proxy(this, {\n`;
        jsCode += `            get(target, prop) {\n`;
        jsCode += `                if (prop in target) {\n`;
        jsCode += `                    return target[prop];\n`;
        jsCode += `                }\n`;
        jsCode += `                if (typeof prop === 'string' && prop !== 'then' && !prop.startsWith('_')) {\n`;
        jsCode += `                    const el = document.getElementById(prop);\n`;
        jsCode += `                    if (el) return el;\n`;
        jsCode += `                }\n`;
        jsCode += `                return undefined;\n`;
        jsCode += `            }\n`;
        jsCode += `        });\n`;
        jsCode += `    }\n\n`;

        // Generate Getters for all statically detected IDs (ensures IDE autocomplete and live DOM access)
        elementsWithId.forEach(id => {
            const propName = id.replace(/-([a-z0-9])/g, g => g[1].toUpperCase());
            jsCode += `    get ${propName}() {\n`;
            jsCode += `        return document.getElementById('${id}');\n`;
            jsCode += `    }\n\n`;
        });

        jsCode += `    /**\n`;
        jsCode += `     * Selects multiple elements within this view\n`;
        jsCode += `     * @param {string} selector - CSS Selector (e.g., '.my-class', '[data-id]')\n`;
        jsCode += `     * @returns {Array<HTMLElement>} Native array with the found elements\n`;
        jsCode += `     */\n`;
        jsCode += `    query(selector) {\n`;
        jsCode += `        const root = document.getElementById('${rootId}') || document;\n`;
        jsCode += `        return Array.from(root.querySelectorAll(selector));\n`;
        jsCode += `    }\n\n`;
        jsCode += `    // ==========================================\n`;
        jsCode += `    // JSFORM AUTO-BINDING ENGINE (Reflection & Event Delegation)\n`;
        jsCode += `    // ==========================================\n`;
        jsCode += `    autoBindEvents() {\n`;
        jsCode += `        const methods = Object.getOwnPropertyNames(Object.getPrototypeOf(this));\n`;
        jsCode += `        const rootElement = document.getElementById('${rootId}') || document;\n`;
        jsCode += `        methods.forEach(method => {\n`;
        jsCode += `            if (method.includes('_') && !method.startsWith('_')) {\n`;
        jsCode += `                const lastUnderscore = method.lastIndexOf('_');\n`;
        jsCode += `                const targetName = method.substring(0, lastUnderscore);\n`;
        jsCode += `                const eventType = method.substring(lastUnderscore + 1);\n`;
        jsCode += `                if (targetName.startsWith('cls_') && typeof this[method] === 'function') {\n`;
        jsCode += `                    const rawClassName = targetName.substring(4);\n`;
        jsCode += `                    const className = rawClassName.replace(/_/g, '-');\n`;
        jsCode += `                    rootElement.addEventListener(eventType, (e) => {\n`;
        jsCode += `                        const targetElement = e.target.closest('.' + className) || e.target.closest('.' + rawClassName);\n`;
        jsCode += `                        if (targetElement && (rootElement === document || rootElement.contains(targetElement))) {\n`;
        jsCode += `                            this[method](e, targetElement);\n`;
        jsCode += `                        }\n`;
        jsCode += `                    });\n`;
        jsCode += `                    console.log(\`[JSForm AutoBind Class - Delegated] .\${className} -> \${eventType}\`);\n`;
        jsCode += `                } else if (typeof this[method] === 'function') {\n`;
        jsCode += `                    rootElement.addEventListener(eventType, (e) => {\n`;
        jsCode += `                        const targetElement = e.target.closest('#' + targetName);\n`;
        jsCode += `                        if (targetElement && (rootElement === document || rootElement.contains(targetElement))) {\n`;
        jsCode += `                            this[method](e, targetElement);\n`;
        jsCode += `                        }\n`;
        jsCode += `                    });\n`;
        jsCode += `                    console.log(\`[JSForm AutoBind ID - Delegated] #\${targetName} -> \${eventType}\`);\n`;
        jsCode += `                }\n`;
        jsCode += `            }\n`;
        jsCode += `        });\n`;
        jsCode += `    }\n}\n`;

        // Write the updated class to the file system
        const designerPath = path.join(path.dirname(htmlPath), `${baseName}.designer.js`);
        fs.writeFileSync(designerPath, jsCode);
        
    } catch (error) {
        console.error(`   -> ❌ [ERROR]:`, error.message);
    }
}