// core/compiler.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chokidar from 'chokidar';
import * as cheerio from 'cheerio';

// Resolve absolute paths for ES Modules compatibility
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

console.log("🚀 JSForm Compiler starting...");

// ==========================================
// 1. PROJECT SCAFFOLDING
// Automatically creates the required directory structure.
// ==========================================
const baseFolders = [
    'assets/css',
    'assets/img',
    'assets/vendors',
    'app/forms',
    'app/services'
];

console.log("🛠️  Checking project structure...");
baseFolders.forEach(folder => {
    const fullPath = path.join(rootDir, folder);
    if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
        console.log(`   -> [Created] Folder: ${folder}`);
    }
});

// ==========================================
// 2. FILE WATCHER INITIALIZATION
// Monitors the 'app/forms' directory for changes.
// ==========================================
const formsDir = path.join(rootDir, 'app', 'forms');

const watcher = chokidar.watch(formsDir, {
    ignored: /node_modules/,
    persistent: true,
    ignoreInitial: true // Prevents firing events for existing files on startup
});

watcher.on('ready', () => {
    console.log("\n👀 JSForm is ready. Create a new folder in app/forms to generate a module!");
});

// ==========================================
// 3. AUTO-GENERATION ON FOLDER CREATION
// Scaffolds the .html, .designer.js, and .controller.js files.
// ==========================================
watcher.on('addDir', (dirPath) => {
    if (dirPath === formsDir) return; // Ignore the root forms directory

    const folderName = path.basename(dirPath);
    const baseName = folderName;
    const className = folderName.charAt(0).toUpperCase() + folderName.slice(1);

    const htmlFile = path.join(dirPath, `${baseName}.html`);
    const designerFile = path.join(dirPath, `${baseName}.designer.js`);
    const controllerFile = path.join(dirPath, `${baseName}.controller.js`);

    if (!fs.existsSync(htmlFile)) {
        console.log(`\n[JSForm] 🌟 New view detected: ${folderName}. Generating skeleton...`);

        // HTML Template
        const htmlContent = `<div id="${baseName}Panel">\n    <h2>View: ${className}</h2>\n    \n</div>`;
        fs.writeFileSync(htmlFile, htmlContent);

        const propName = baseName.replace(/-([a-z0-9])/g, g => g[1].toUpperCase());
        const designerContent = `// AUTO-GENERATED BY JSFORM - DO NOT MODIFY\nexport class ${className}Designer {\n    constructor() {\n        this.${propName}Panel = document.getElementById('${baseName}Panel');\n        this.autoBindEvents();\n    }\n\n    /**\n     * Selects multiple elements within this view\n     * @param {string} selector - CSS Selector (e.g., '.my-class', '[data-id]')\n     * @returns {Array<HTMLElement>} Native array with the found elements\n     */\n    query(selector) {\n        const root = Object.values(this).find(val => val instanceof HTMLElement) || document;\n        return Array.from(root.querySelectorAll(selector));\n    }\n\n    // ==========================================\n    // JSFORM AUTO-BINDING ENGINE (Reflection)\n    // ==========================================\n    autoBindEvents() {\n        const methods = Object.getOwnPropertyNames(Object.getPrototypeOf(this));\n        methods.forEach(method => {\n            if (method.includes('_')) {\n                const lastUnderscore = method.lastIndexOf('_');\n                const targetName = method.substring(0, lastUnderscore);\n                const eventType = method.substring(lastUnderscore + 1);\n                if (this[targetName] && typeof this[method] === 'function') {\n                    this[targetName].addEventListener(eventType, this[method].bind(this));\n                    console.log(\`[JSForm AutoBind ID] \${targetName} -> \${eventType}\`);\n                } else if (targetName.startsWith('cls_') && typeof this[method] === 'function') {\n                    const rawClassName = targetName.substring(4);\n                    const className = rawClassName.replace(/_/g, '-');\n                    // Usamos delegación de eventos en el document para soportar elementos dinámicos\n                    document.addEventListener(eventType, (e) => {\n                        const targetElement = e.target.closest('.' + className) || e.target.closest('.' + rawClassName);\n                        if (targetElement) {\n                            this[method](e, targetElement);\n                        }\n                    });\n                    console.log(\`[JSForm AutoBind Class - Delegated] .\${className} -> \${eventType}\`);\n                }\n            }\n        });\n    }\n}\n`;
        fs.writeFileSync(designerFile, designerContent);

        // Controller Template (Clean Business Logic)
        const controllerContent = `import { ${className}Designer } from './${baseName}.designer.js';

export class ${className}Controller extends ${className}Designer {
    constructor(parameters) {
        super();
        this.parameters = parameters;
        this.init();
    }

    init() {
        console.log("${className} view loaded successfully.");
        // Ya no necesitas hacer this.btnSave.onclick = ...
        // Simplemente crea el método btnSave_click(e) { ... } abajo
    }

    // onDestroy() {
    //    // Limpieza de memoria (timers, eventos globales, etc.)
    // }
}\n`;
        fs.writeFileSync(controllerFile, controllerContent);

        console.log(`   -> ✅ Files created: .html, .designer.js, and .controller.js`);
    }
});

// ==========================================
// 4. DESIGNER UPDATE ON HTML MODIFICATION
// Parses the HTML AST and updates DOM bindings in the Designer class.
// ==========================================
watcher.on('change', (filePath) => {
    if (filePath.endsWith('.html')) {
        console.log(`\n[JSForm] 💾 HTML modified: ${path.basename(filePath)}. Updating Designer...`);
        generateDesigner(filePath);
    }
});

/**
 * Parses an HTML file and generates the corresponding .designer.js class.
 * @param {string} htmlPath - Absolute path to the HTML file.
 */
function generateDesigner(htmlPath) {
    try {
        const htmlContent = fs.readFileSync(htmlPath, 'utf-8');
        
        // Handle different cheerio module export styles
        const loadCheerio = cheerio.load || cheerio.default.load;
        const $ = loadCheerio(htmlContent);
        
        // Extract all elements with an 'id' attribute
        const elementsWithId = [];
        $('[id]').each((index, element) => {
            elementsWithId.push($(element).attr('id'));
        });

        const folderName = path.basename(path.dirname(htmlPath));
        const baseName = path.basename(htmlPath, '.html');
        const className = folderName.charAt(0).toUpperCase() + folderName.slice(1);

        // Build the ES6 class code
        let jsCode = `// AUTO-GENERATED BY JSFORM - DO NOT MODIFY\nexport class ${className}Designer {\n    constructor() {\n`;
        elementsWithId.forEach(id => {
            const propName = id.replace(/-([a-z0-9])/g, g => g[1].toUpperCase());
            jsCode += `        this.${propName} = document.getElementById('${id}');\n`;
        });
        jsCode += `        this.autoBindEvents();\n`;
        jsCode += `    }\n\n`;
        jsCode += `    /**\n`;
        jsCode += `     * Selects multiple elements within this view\n`;
        jsCode += `     * @param {string} selector - CSS Selector (e.g., '.my-class', '[data-id]')\n`;
        jsCode += `     * @returns {Array<HTMLElement>} Native array with the found elements\n`;
        jsCode += `     */\n`;
        jsCode += `    query(selector) {\n`;
        jsCode += `        const root = Object.values(this).find(val => val instanceof HTMLElement) || document;\n`;
        jsCode += `        return Array.from(root.querySelectorAll(selector));\n`;
        jsCode += `    }\n\n`;
        jsCode += `    // ==========================================\n`;
        jsCode += `    // JSFORM AUTO-BINDING ENGINE (Reflection)\n`;
        jsCode += `    // ==========================================\n`;
        jsCode += `    autoBindEvents() {\n`;
        jsCode += `        const methods = Object.getOwnPropertyNames(Object.getPrototypeOf(this));\n`;
        jsCode += `        methods.forEach(method => {\n`;
        jsCode += `            if (method.includes('_')) {\n`;
        jsCode += `                const lastUnderscore = method.lastIndexOf('_');\n`;
        jsCode += `                const targetName = method.substring(0, lastUnderscore);\n`;
        jsCode += `                const eventType = method.substring(lastUnderscore + 1);\n`;
        jsCode += `                if (this[targetName] && typeof this[method] === 'function') {\n`;
        jsCode += `                    this[targetName].addEventListener(eventType, this[method].bind(this));\n`;
        jsCode += `                    console.log(\`[JSForm AutoBind ID] \${targetName} -> \${eventType}\`);\n`;
        jsCode += `                } else if (targetName.startsWith('cls_') && typeof this[method] === 'function') {\n`;
        jsCode += `                    const rawClassName = targetName.substring(4);\n`;
        jsCode += `                    const className = rawClassName.replace(/_/g, '-');\n`;
        jsCode += `                    // Usamos delegación de eventos en el document para soportar elementos dinámicos\n`;
        jsCode += `                    document.addEventListener(eventType, (e) => {\n`;
        jsCode += `                        const targetElement = e.target.closest('.' + className) || e.target.closest('.' + rawClassName);\n`;
        jsCode += `                        if (targetElement) {\n`;
        jsCode += `                            this[method](e, targetElement);\n`;
        jsCode += `                        }\n`;
        jsCode += `                    });\n`;
        jsCode += `                    console.log(\`[JSForm AutoBind Class - Delegated] .\${className} -> \${eventType}\`);\n`;
        jsCode += `                }\n`;
        jsCode += `            }\n`;
        jsCode += `        });\n`;
        jsCode += `    }\n}\n`;

        // Write the updated class to the file system
        const designerPath = path.join(path.dirname(htmlPath), `${baseName}.designer.js`);
        fs.writeFileSync(designerPath, jsCode);
        
    } catch (error) {
        console.error(`   -> ❌ [ERROR]:`, error.message);
    }
}