// core/compiler.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import chokidar from 'chokidar';
import * as cheerio from 'cheerio';

// Resolve absolute paths for ES Modules compatibility
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

console.log("🚀 JSForm Compiler starting...");

// ==========================================
// 1. PROJECT SCAFFOLDING
// Automatically creates the required directory structure.
// ==========================================
const baseFolders = [
    'assets/css',
    'assets/img',
    'assets/vendors',
    'app/forms',
    'app/services'
];

console.log("🛠️  Checking project structure...");
baseFolders.forEach(folder => {
    const fullPath = path.join(rootDir, folder);
    if (!fs.existsSync(fullPath)) {
        fs.mkdirSync(fullPath, { recursive: true });
        console.log(`   -> [Created] Folder: ${folder}`);
    }
});

// ==========================================
// 2. FILE WATCHER INITIALIZATION
// Monitors the 'app/forms' directory for changes.
// ==========================================
const formsDir = path.join(rootDir, 'app', 'forms');

const watcher = chokidar.watch(formsDir, {
    ignored: /node_modules/,
    persistent: true,
    ignoreInitial: true // Prevents firing events for existing files on startup
});

watcher.on('ready', () => {
    console.log("\n👀 JSForm is ready. Create a new folder in app/forms to generate a module!");
});

// ==========================================
// 3. AUTO-GENERATION ON FOLDER CREATION
// Scaffolds the .html, .designer.js, and .controller.js files.
// ==========================================
watcher.on('addDir', (dirPath) => {
    if (dirPath === formsDir) return; // Ignore the root forms directory

    const folderName = path.basename(dirPath);
    const baseName = folderName.toLowerCase();
    const className = folderName.charAt(0).toUpperCase() + folderName.slice(1);

    const htmlFile = path.join(dirPath, `${baseName}.html`);
    const designerFile = path.join(dirPath, `${baseName}.designer.js`);
    const controllerFile = path.join(dirPath, `${baseName}.controller.js`);

    if (!fs.existsSync(htmlFile)) {
        console.log(`\n[JSForm] 🌟 New view detected: ${folderName}. Generating skeleton...`);

        // HTML Template
        const htmlContent = `<div id="${baseName}Panel">\n    <h2>View: ${className}</h2>\n    \n</div>`;
        fs.writeFileSync(htmlFile, htmlContent);

        // Designer Template (Handles DOM bindings)
        const designerContent = `// AUTO-GENERATED BY JSFORM - DO NOT MODIFY\nexport class ${className}Designer {\n    constructor() {\n        this.${baseName}Panel = document.getElementById('${baseName}Panel');\n    }\n}\n`;
        fs.writeFileSync(designerFile, designerContent);

        // Controller Template (Handles business logic AND Reflection Auto-Binding)
        // AQUI INYECTAMOS LA LÓGICA DE REFLEXIÓN TIPO WINFORMS
        const controllerContent = `import { ${className}Designer } from './${baseName}.designer.js';

export class ${className}Controller extends ${className}Designer {
    constructor(parameters) {
        super();
        this.parameters = parameters;
        this.autoBindEvents(); // <--- Llamada a la magia de reflexión
        this.init();
    }

    init() {
        console.log("${className} view loaded successfully.");
        // Ya no necesitas hacer this.btnSave.onclick = ...
        // Simplemente crea el método btnSave_click(e) { ... } abajo
    }

    // ==========================================
    // JSFORM AUTO-BINDING ENGINE (Reflection)
    // ==========================================
    autoBindEvents() {
        const methods = Object.getOwnPropertyNames(Object.getPrototypeOf(this));
        
        methods.forEach(method => {
            if (method.includes('_')) {
                // Fix: Usar lastIndexOf para permitir guiones bajos en el ID del elemento (ej. user_name_click)
                const lastUnderscore = method.lastIndexOf('_');
                const elementId = method.substring(0, lastUnderscore);
                const eventType = method.substring(lastUnderscore + 1);
                
                // Si el elemento existe en el Designer y el método es una función, los enlazamos
                if (this[elementId] && typeof this[method] === 'function') {
                    this[elementId].addEventListener(eventType, this[method].bind(this));
                    console.log(\`[JSForm AutoBind] \${elementId} -> \${eventType}\`);
                }
            }
        });
    }
}\n`;
        fs.writeFileSync(controllerFile, controllerContent);

        console.log(`   -> ✅ Files created: .html, .designer.js, and .controller.js`);
    }
});

// ==========================================
// 4. DESIGNER UPDATE ON HTML MODIFICATION
// Parses the HTML AST and updates DOM bindings in the Designer class.
// ==========================================
watcher.on('change', (filePath) => {
    if (filePath.endsWith('.html')) {
        console.log(`\n[JSForm] 💾 HTML modified: ${path.basename(filePath)}. Updating Designer...`);
        generateDesigner(filePath);
    }
});

/**
 * Parses an HTML file and generates the corresponding .designer.js class.
 * @param {string} htmlPath - Absolute path to the HTML file.
 */
function generateDesigner(htmlPath) {
    try {
        const htmlContent = fs.readFileSync(htmlPath, 'utf-8');
        
        // Handle different cheerio module export styles
        const loadCheerio = cheerio.load || cheerio.default.load;
        const $ = loadCheerio(htmlContent);
        
        // Extract all elements with an 'id' attribute
        const elementsWithId = [];
        $('[id]').each((index, element) => {
            elementsWithId.push($(element).attr('id'));
        });

        const folderName = path.basename(path.dirname(htmlPath));
        const baseName = path.basename(htmlPath, '.html');
        const className = folderName.charAt(0).toUpperCase() + folderName.slice(1);

        // Build the ES6 class code
        let jsCode = `// AUTO-GENERATED BY JSFORM - DO NOT MODIFY\nexport class ${className}Designer {\n    constructor() {\n`;
        elementsWithId.forEach(id => {
            jsCode += `        this.${id} = document.getElementById('${id}');\n`;
        });
        jsCode += `    }\n}\n`;

        // Write the updated class to the file system
        const designerPath = path.join(path.dirname(htmlPath), `${baseName}.designer.js`);
        fs.writeFileSync(designerPath, jsCode);
        
    } catch (error) {
        console.error(`   -> ❌ [ERROR]:`, error.message);
    }
}